name: "quark"
description: "quarkaudio project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  file_picker: ^10.1.1
  audiotags: ^1.4.5
  interactive_slider: ^0.5.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.1
  hive: ^2.2.3
  async: ^2.12.0
  http: ^1.4.0
  dio: ^5.8.0+1
  flutter_colorpicker: ^1.1.0
  logging: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/play.png
      - assets/icon.png
