name: quark
description: "quarkaudio player. penises development group entertaiment."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  hive: ^2.2.3
  interactive_slider: ^0.5.1
  logging: ^1.3.0
  path_provider: ^2.1.5
  http: ^1.4.0
  # audiotags: ^1.4.5
  audioplayers: ^6.5.0
  dio: ^5.8.0+1
  webview_flutter: ^4.13.0
  audio_metadata_reader: ^1.4.2
  flutter_rust_bridge: 2.5.0
  smtc_windows: ^1.0.0
  audio_service_mpris: ^0.2.0
  audio_service: ^0.18.18
  flutter_inappwebview: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/play.png
      - assets/icon.png
