name: quark
description: "quarkaudio player. penises development group entertaiment."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  hive: ^2.2.3
  interactive_slider: ^0.5.1
  logging: ^1.3.0
  path_provider: ^2.1.5
  http: ^1.4.0
  audiotags: ^1.4.5
  audioplayers: ^6.5.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/play.png
      - assets/icon.png
